# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd293c31bcb057a2f664a08f461a4af4220e2c05772801a0154af9db3efd5c0a9f3cdd34b0a3772de1f22402c40cab8b2ec90eecd570b3557da32e0337af17a9
  google_client_id: 563607211746-7avqfkkm0181sopj0lphv3ei8q7r6kko.apps.googleusercontent.com
  google_client_secret: a39eDJEqdzv4wt3gWP3ujxgC


test:
  secret_key_base: a4fad4cd2aec9e1cefad3eba801821e0332a44bfd9392774f9c1ebf3b1331ef24db673996a21a4c12d5fbeefb5b0f2f5ce12b0a2b4f311eca1b15d64cbc27d28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["563607211746-7avqfkkm0181sopj0lphv3ei8q7r6kko.apps.googleusercontent.com"] %>
  google_client_secret: <%= ENV["a39eDJEqdzv4wt3gWP3ujxgC"] %>